# NumPy 

NumPy (o Numpy) es un módulo de Algebra Lineal para Python.  La razón por la que es tan importante para la Ciencia de Datos con Python es que casi todas los módulos en el Ecosistema PyData de Python se apoyan en NumPy como uno de sus pilares.

NumPy también es increíblemente rápido, ya que tiene enlaces a librerías de C.  Para mayor información sobre porqué podría querer usar Arreglos en vez de Listas, déle un vistazo a este gran  [post en StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Solamente aprenderemos los fundamentales de Numpy.  Para iniciar, es necesario instalarlo!

## Instrucciones de Instalación

**Se recomienda fuertemente que se instale el Python utilizando la distribución de Anaconda para asegurar que todas las dependencias básicas (como el módulo de Algebra Lineal) estén sincronizadas con el uso de un conda install.  Si tiene instalado el Anaconda, el Numpy se instala desde una terminal o petición de instrucciones y tecleando:**
    
    conda install numpy
    
**Si no tiene Anaconda y no puede, o no quiere instalarlo, refiérase a [La documentación oficial de NumPy para instrucciones en varias instalaciones.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Utilización del NumPy

Una vez se ha instalado el NumPy, se puede importar como un módulo:

In [1]:
import numpy as np

El Numpy tiene muchas funciones y capacidades incorporadas. No las cubriremos todas pero, en vez, nos enfocaremos en algunos de los aspectos más importantes de Numpy: vectores, arreglos, matrices, y generación de números. Empecemos la discusión con Arreglos.

# Arreglos Numpy

Los arreglos NumPy son la principal forma en que utilizaremos NumPy en este curso. Los arreglos Numpy vienen escencialmente en dos variedades: vectores y matrices. Los vectores son estrictamente arreglos 1-d y las matrices son 2-d (pero es importante notar que una matriz puede tener solo una fila o una columna).

Iniciemos nuestra introducción explorando cómo crear arreglos NumPy.

## Creación de Arreglos NumPy

### A partir de una lista de Python

Podemos crear un arreglo directamente convirtiendo una lista o lista de listas:

In [2]:
mi_lista = [1,2,3]
mi_lista

[1, 2, 3]

In [4]:
np.array(mi_lista)

array([1, 2, 3])

In [5]:
mi_matriz = [[1,2,3],[4,5,6],[7,8,9]]
mi_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(mi_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados

Existen muchas formas ya incorporadas para generar Arreglos

### arange

Regresa valores uniformemente espaciados dentro de un intervalo dado.

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros y ones

Generan arreglos de ceros o unos, respectivamente

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Genera números espaciados en forma uniforme a través de un intervalo especificado.

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Crea una matriz identidad

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy también tiene muchas formas para crear arreglos de números aleatorios:

### rand
Crea un arreglo de la forma indicada y lo pobla con muestras aleatorias de una distribución uniforme
etre ``[0, 1)``.

In [16]:
np.random.rand(2)

array([0.95098717, 0.34379233])

In [17]:
np.random.rand(5,5)

array([[0.56333331, 0.77361235, 0.12577265, 0.25835766, 0.88798945],
       [0.70155525, 0.8402126 , 0.26885268, 0.65512853, 0.38756409],
       [0.04025872, 0.5053324 , 0.11524628, 0.40064208, 0.01892526],
       [0.07932188, 0.35467393, 0.18433236, 0.74584064, 0.21834089],
       [0.68149657, 0.49028592, 0.66534798, 0.93113577, 0.22924805]])

### randn

Devuelve una muestra (o muestras) de la distribución "estándard normal". Esto no es como rand ya que esa es uniforme:

In [18]:
np.random.randn(2)

array([-1.15609487,  0.37466542])

In [19]:
np.random.randn(5,5)

array([[-0.12616819,  0.44491068, -0.83775643, -1.0659996 , -1.37705381],
       [ 0.01644365,  0.45851433,  1.31059276,  1.35279397, -0.70132563],
       [ 1.02958904, -0.83226283,  0.23184133,  0.62397033, -1.67473392],
       [ 0.97151006, -0.61276992, -2.13575898,  0.97009693, -0.02417428],
       [-0.58676491, -0.77804841, -1.29137057, -0.2613581 ,  0.82286648]])

### randint
Devuelve enteros aleatorios desde `mínimo` (inclusiv) hasta `máximo` (exclusivo).

In [20]:
np.random.randint(1,100)

40

In [21]:
np.random.randint(1,100,10)

array([94, 62, 75, 22,  2, 16, 19, 11, 94, 89])

## Atributos y Métodos de Arreglos

Veamos algunos atributos y métodos de un arreglo:

In [22]:
arreglo = np.arange(25)
arreglo_azar = np.random.randint(0,50,10)

In [23]:
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arreglo_azar

array([37,  8, 20, 39, 13,  2, 49, 43, 33,  5])

## Reshape
Devuelve un arreglo conteniendo los mismos datos poro con una forma diferente.

In [25]:
arreglo.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estos son métodos útiles para encontrar valores máximos  mínimos, o para encontrar sus posiciones indizadas utilizando argmin o argmax

In [26]:
arreglo_azar

array([37,  8, 20, 39, 13,  2, 49, 43, 33,  5])

In [27]:
arreglo_azar.max()

49

In [28]:
arreglo_azar.argmax()

6

In [29]:
arreglo_azar.min()

2

In [30]:
arreglo_azar.argmin()

5

## Shape

Shape (forma) es un atributo que los arreglos tienen (no es un método):

In [31]:
# Vector
arreglo.shape

(25,)

In [32]:
# Notar los dos conjuntos de corchetes
arreglo.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arreglo.reshape(1,25).shape

(1, 25)

In [34]:
arreglo.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
arreglo.reshape(25,1).shape

(25, 1)

### dtype

Se puede obtener el tipo de datos en el arreglo:

In [36]:
arreglo.dtype

dtype('int32')

# Buen trabajo!